### ISSUE TITLE
Onboarding: Create bike

### ISSUE THREAD

**Issue by casparroelofs** [liskcenterutrecht/lisk.bike#12]
Onboarding means that the Virtual Lock Server creates a wallet for the lock on the lisk.bike sidechain. Now there's a connection between the lock and the pubkey, in the Lisk blockchain.

See 
[] https://github.com/bartwr/lisk-bike-blockchain-app/blob/master/client/create-account.js(url)
[]https://github.com/bartwr/lisk-bike-blockchain-app/blob/master/transactions/create-bike.js(url)

- [x] Lock sends the 'login' command to server
- [x] Server creates wallet for lock using ./client/create-account.js
- [x] Server registers lock onto the blockchain and stores BikeID (=Pubkey) + Imei on VLS using ./client/create-bike.js

**Comment by bartwr** [comment]
Creating a bike works. Registering the bike on the blockchain as well.

This is how it looks atm. Works. Issue closed: https://youtu.be/t3xNBDrqJXg
