### ISSUE TITLE
Testing custom transactions

### ISSUE THREAD

**Issue by casparroelofs** [liskcenterutrecht/lisk.bike#14]
Custom transactions must be tested both in terminal and webapp

Terminal testing:

- [x] Create-account.js @Sus4nne 
- [x] Create-bike.js @Sus4nne 
- [x] Update-bike-location.js 
- [ ] Update-lock-status.js

**Comment by casparroelofs** [comment]
Deze zal geupdate worden naarmate er meer transacties in t project beschreven staan
Lukt me niet om Marc te taggen in de checklist..

**Comment by bartwr** [comment]
All features are tested. For code, see: https://github.com/liskcenterutrecht/lisk.bike/tree/master/app/imports/api/lisk-blockchain/tests

For a screencast of the working functionality, see: https://github.com/liskcenterutrecht/lisk.bike/issues/18#issuecomment-552495823
