### ISSUE TITLE
prepare and start rental

### ISSUE THREAD

**Issue by casparroelofs** [liskcenterutrecht/lisk.bike#18]
Before a rental can be initiated, the status of the selected bike and eligibility of the user are checked by the userapp. 

Bike status:

- [x] Userapp_Read_GPS location (BikeID)
- [x] Userapp_read_Lock status (Bike ID; 'closed')
- [x] Userapp_read_Rental status (Bike ID; 'ended')

User legibility:

- [x] Userapp_Read_Deposit Amount(BikeID)
- [x] Userapp_read_Funds (UserWallet; '>deposit amount')
- [ ] Userapp_check proximity user to selected bike???

Once conditions are met, a deposit is sent from UserWallet to BikeID, a command_open_lock transaction and rental status is updated to started.

- [x] Userapp_Send Deposit (UserWallet;BikeID;Deposit Amount)
- [x] Userapp_Send_Request-open-Lock (BikeID;UserID)
- [x] Userapp_Send_RentalStatus (BikeID;UserID;Started)

**Comment by bartwr** [comment]
The following functionality is done:

- See available bikes in a list
- Click the bike you want to rent
- Rent a bike
- Move the bike
- Lock the bike & end rental

All major actions are recorded to the blockchain. For a screencast, see https://youtu.be/ADvg4Lr9huA
