### ISSUE TITLE
Preparing Workshop in Berlin

### ISSUE THREAD

**Issue by casparroelofs** [liskcenterutrecht/lisk.bike#20]
In November, we will give a workshop at Lisk HQ. We should decide:

- [ ] Who will be present?
- [ ] How much of an introduction to LISK SDK will we need to give or is already given by others?
- [ ] How will we present the work that we have done?
- [ ] How will we make it an interactive learning experience for participants?

**Comment by bartwr** [comment]
What type of audience do we expect? Traders? Lisk delegates? Blockchain dinosaurs? Devvers? Activists? If we have an idea of the type of people, we can target our session more specific.

A bit on the concept of custom transactions (and how this is different from smart contracts) could be nice.

Running your own Lisk independent chain / creating your coin, a how to.

Bike sharing, the story, concept, results & future.

A bit on the blockchain/meetup ecosystem, and how cool projects like this start by collaborating.

^ Some ideas that work for every audience.

**Comment by mosbuma** [comment]
Specs for the workshop as communicated with Lisk:

At LCU we are discussing the presentation of the first version of the lisk.bike project at the Lisk meetup in november.

We are planning to coming to Berlin and thought it might be a fun idea to present the results of the project in a workshop.

Attendees can then get some hands on experience with the Lisk platform and SDK. We are thinking about a 2 hour workshop for max. 20 persons.

Is this something that would fit in the conference schedule? Alternatively / in addition to the workshop we can do a presentation about the project.

Requirements for the workshop would be: room with seating for 20 px, beamer/TV, power outlets, wifi and "Bring your own laptop"

I was thinking about a technical hands-on session where developers can create their own (virtual) lisk bike and rent it out using the lisk.bike app. Then explain how the rental transactions work and have people use the lisk blockchain explorer to see what happens on the blockchain.

- Do you have an idea of the type of visitors that will come to the congress?

Lisk: 
* congress will target experienced JS developers
* on the congress program:

◴ 10:00 - 12:00 - Lisk.bike Workshop

Learn about the eco-friendly blockchain use-case built by Lisk developer community in the Netherlands.
