### ISSUE TITLE
Create node.js library for BL10 bike lock

### ISSUE THREAD

**Issue by mosbuma** [liskcenterutrecht/lisk.bike#9]
- [ ] use zandbak/testbl10 project as basis
- create node.js module that can decode / encode all info from the bike lock protocol
  - [x] decode login info packet
  - [x] send server reply for login info packet
  - [x] decode heartbeat packet
  - [x] send server reply for heartbeat packet
  - [x] decode gps location information packet
  - [x] send server reply for gps location information packet
  - [X ] send online command to lock
  - [x] decode online command lock reply
  - [x] decode information transmission packet
  - [x] send server reply for information transmission packet

- wifi inforrmation packet (nice to have)
  - [x] check if this functionality works in the lock
  - [x] decode wifi information packet
  - [x] send server reply for wifi information packet

- [ ] create suitable data structure for tracking lock status over sessions

**Comment by casparroelofs** [comment]
@mosbuma is dit het stuk waar je afgelopen maandag bijvoorbeeld op doelde toen je zei dat je bezig was om het slot te doorgronden, en bijvoorbeeld het stuk waar je de GPS van het slot uitleest?
